//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMPart
    {
        public int Id { get; set; }
        public string JobNumber { get; set; }
        public int PartId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
