//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOM_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.BOMParts = new HashSet<BOMPart>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string PartNumber { get; set; }
        public string Link { get; set; }
        public string Price { get; set; }
        public Nullable<int> CatergoeryId { get; set; }
        public string Supplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMPart> BOMParts { get; set; }
        public virtual Catergoery Catergoery { get; set; }
    }
}
